### ISSUE TITLE
error loading data in SPM.mat

### ISSUE THREAD

**Issue by mike21499** [allefeld/cvmanova#23]
Hi there

I'm receiving an error while loading the SPM.mat file using cvManovaSearchlight.m:

loading data
 via X:\SPM.mat
 153926 in-mask voxels
 no region mask
 reading images
Undefined function 'diff' for input arguments of type 'cell'.

Error in loadDataSPM (line 105)
pattern(~all(diff(SPM.xY.P) == 0)) = '?';

Error in cvManovaSearchlight (line 47)
[Ys, Xs, mask, misc] = loadDataSPM(dirName);

thanks for help! 
cheers, mike

**Comment by mike21499** [comment]
sry. Don't take a second-level SPM.mat

**Comment by allefeld** [comment]
@mike21499 , no that cannot work. :) But maybe I should catch that and display a warning. Thanks!
