### ISSUE TITLE
minor bugs in cvManovaTest

### ISSUE THREAD

**Issue by anaston** [allefeld/cvmanova#24]
Hi Allefeld,

Great work and very much appreciated for making the toolbox available!

I cloned the repo today and went through the example with the cvManovaTest scripts, where I encountered 3 minor problems:

1. websave was introduced in MATLAB R2014b, so I needed to download the dataset manually since I am using MATLAB R2014a.
see line 8 in cvManoveTest_getdata.m

2. sprintf runs in trouble in Windows, since the escape character is the same as the file separator.
see line 10 of cvManovaTest_preprocess.m
see line 19 of cvManovaTest_model.m

3. cvManovaTest_preprocess.m uses the same variables (e.g. nRuns) as cvManoveTest_getdata.m. In case the design has been created earlier in another session (exist(fnDesign, 'file') evaluates true in cvManovaTest_getdata.m), then these variables are missing during running cvManovaTest_preprocess.m.

After fixing these minor issues, the code runs smoothly.

Thanks and best,
Agoston

**Comment by allefeld** [comment]
@anaston, thanks for the heads-up, I'll look into this!

**Comment by charujing** [comment]
Hi Agoston, I also met similar errors. Could you send me your modified scripts?
Thanks.
rujing

**Comment by anaston** [comment]
Hi Rujing, I am sorry, but I moved lab and having difficulties to dig up the scripts. I hope you manage to modify the code, perhaps, Allefeld can also help you out. Cheers, Agoston

**Comment by charujing** [comment]
Hi Agoston, Thanks for your reply. It's ok. I tried by myself, but it's not working. Hope Allefeld could help me.
Rujing

**Comment by allefeld** [comment]
Hello @anaston and @charujing, really sorry for not getting back to you earlier. I'm in the process of changing academic institutions and countries, and was insanely busy. I hope things will quiet down in the next weeks.

**Comment by Remi-Gau** [comment]
See pull request #32. It should fix those issues.

@charujing : you can maybe test it by using the `remi-dev` branch on my repository.

**Comment by allefeld** [comment]
@anaston @charujing  could you please check whether the latest commit
https://github.com/allefeld/cvmanova/tree/7d285b933cd328cdb1dad188d68f1c84d2248129
solves the problem?

**Comment by allefeld** [comment]
I assume that this is fixed by #32.

**Comment by allefeld** [comment]
I assume that this is fixed by #32, if not please someone let me know.
