### ISSUE TITLE
check whether alternate loading method works reliably

### ISSUE THREAD

**Issue by allefeld** [allefeld/cvmanova#26]

**Comment by allefeld** [comment]
Hi @Remi-Gau, I think you meant the issue "matlabbatch error" #31?

**Comment by Remi-Gau** [comment]
> Hi @Remi-Gau, I think you meant the issue "matlabbatch error" #31?

indeed. :-)

**Comment by allefeld** [comment]
The "alternate loading method" has been in use for a while now, seems to be okay.
