### ISSUE TITLE
Pattern and activation

### ISSUE THREAD

**Issue by verve9** [allefeld/cvmanova#28]
Hi,

This is not the coding issue but an open question. I was wondering if cvMANOVA can capture both 'activation' and 'neural pattern information' of interest. I ask this question because we want to compare standard searchlight and cvMANOVA, and we found standard searchlight was sensitive to typical activation region and others, while cvMANOVA was not sensitive to typical activation region. Is there any way how the method handles differences in activation magnitude?

Thank you.

**Comment by allefeld** [comment]
not a code issue
