### ISSUE TITLE
cvManovaRegion

### ISSUE THREAD

**Issue by verve9** [allefeld/cvmanova#29]
Hi,

I have another issue with cvManovaRegion. The issue is that this works well with some ROI mask, but does not work with some other ROI masks. In my case, I created three ROI region masks, (cell array of 3D volumes of 1 and 0). ROI 1 and 2 have some overlappings and ROI 3 is union of ROIs 1 and 2. The problem is that cvManovaRegion works only for ROI 2, but and ROI 1 and 3, and the error message is that,

data insufficient for the 1259 voxels of region 1!
data insufficient for the 1526 voxels of region 3!

Can you please help? Thanks.

**Comment by allefeld** [comment]
Please read the section "Regularization" <https://github.com/allefeld/cvmanova#regularization> of the README. These regions are simply too large for the error covariance to be properly estimated.
