### ISSUE TITLE
matlabbatch error

### ISSUE THREAD

**Issue by charujing** [allefeld/cvmanova#31]
When running cvManovaTest, it echos this errors. Thanks very much.

>> cvManovaTest
analyzing data of subj1 from Haxby et al. (2001)
37  cvManovaTest_model
estimating model

------------------------------------------------------------------------
08-Aug-2019 18:32:14 - Running job #1
------------------------------------------------------------------------
08-Aug-2019 18:32:14 - Running 'Model estimation'

SPM12: spm_spm (v7120)                             18:32:16 - 08/08/2019
========================================================================
08-Aug-2019 18:32:16 - Failed  'Model estimation'
错误使用 spm_spm (line 309)
Data have not been specified.
In file "/Volumes/VMware Shared Folders/E/vm_mac_matlab/spm12/spm_spm.m" (v7120), function "spm_spm" at line 309.
In file "/Volumes/VMware Shared Folders/E/vm_mac_matlab/spm12/config/spm_run_fmri_est.m" (v7354), function "spm_run_fmri_est" at line 36.

The following modules did not run:
Failed: Model estimation

错误使用 MATLABbatch system
Job execution failed. The full log of this run can be found in MATLAB command
window, starting with the lines (look for the line showing the exact #job as
displayed in this error message)
------------------
Running job #1
------------------

**Comment by allefeld** [comment]
@charujing could you please check whether the latest commit
https://github.com/allefeld/cvmanova/tree/7d285b933cd328cdb1dad188d68f1c84d2248129
solves the problem?

**Comment by allefeld** [comment]
I assume that this is fixed by #32, if not please someone let me know.
